# Generated by Django 2.2.1 on 2020-11-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20201128_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sort_order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
