# Generated by Django 2.2.1 on 2020-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20201128_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ManyToManyField(blank=True, related_name='tests', to='quizzes.Quiz')),
            ],
        ),
    ]
