# Generated by Django 2.2.1 on 2020-11-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_testclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
