# Generated by Django 2.2.1 on 2020-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20201129_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date ended'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date started'),
        ),
    ]
