# Generated by Django 2.2.1 on 2020-11-30 00:03

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_auto_20201130_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='answer',
            name='test_blank',
            field=jsonfield.fields.JSONField(default='', verbose_name='Тестовый пока'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='quizzes.Question', verbose_name='Вопросы'),
        ),
    ]
