# Generated by Django 2.2.1 on 2020-11-30 01:09

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_auto_20201130_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='Идентификатор пользователя')),
                ('pass_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата прохождения')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.Quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Прохождение',
                'verbose_name_plural': 'Прохождения',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', jsonfield.fields.JSONField(default='', verbose_name='Ответ')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.Attempt', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
