# Generated by Django 2.2.1 on 2020-11-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_answer_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.Quiz', verbose_name='Квиз'),
        ),
    ]
