# Generated by Django 2.2.1 on 2020-11-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_auto_20201130_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.Quiz', verbose_name='Квиз'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='Идентификатор пользователя'),
        ),
    ]
